name:        elliptic-curve
version:     0.1.0
synopsis:    Elliptic curve library
description: Elliptic curve library
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/elliptic-curve
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - MultiParamTypeClasses
  - TypeFamilyDependencies
  - UndecidableInstances

dependencies:
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - galois-field

extra-source-files:
  - README.md
  - ChangeLog.md

library:
  exposed-modules:
    - Curve
    - Curve.ShortWeierstrass
    - Curve.ShortWeierstrass.BLS12_381
    - Curve.ShortWeierstrass.BLS12_381.G1
    - Curve.ShortWeierstrass.BLS12_381.G2
    - Curve.TwistedEdwards
    - Curve.TwistedEdwards.JubJub
  ghc-options:
    - -Wall
    - -fno-warn-orphans
  source-dirs:
    - src

tests:
  elliptic-curve-tests:
    main: Main
    dependencies:
      - base >= 4.7 && < 5
      - protolude >= 0.2
      - tasty
      - tasty-discover
      - tasty-quickcheck
    source-dirs:
      - tests
      - src

benchmarks:
  elliptic-curve-benchmarks:
    main: Main
    dependencies:
      - base >= 4.7 && < 5
      - protolude >= 0.2
      - criterion
    source-dirs:
      - benchmarks
      - src
