name:        elliptic-curve
version:     0.1.0
synopsis:    Elliptic curve library
description: Elliptic curve library
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/elliptic-curve
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - MultiParamTypeClasses
  - TypeFamilyDependencies
  - UndecidableInstances

dependencies:
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - galois-field
  - tasty-hunit
  - tasty-quickcheck

extra-source-files:
  - README.md
  - ChangeLog.md

library:
  exposed-modules:
    - Curve
    - Curve.BinaryWeierstrass
    - Curve.BinaryWeierstrass.SECT113R1
    - Curve.BinaryWeierstrass.SECT113R2
    - Curve.BinaryWeierstrass.SECT131R1
    - Curve.BinaryWeierstrass.SECT131R2
    - Curve.BinaryWeierstrass.SECT163K1
    - Curve.BinaryWeierstrass.SECT163R1
    - Curve.BinaryWeierstrass.SECT163R2
    - Curve.BinaryWeierstrass.SECT193R1
    - Curve.BinaryWeierstrass.SECT193R2
    - Curve.BinaryWeierstrass.SECT233K1
    - Curve.BinaryWeierstrass.SECT233R1
    - Curve.BinaryWeierstrass.SECT239K1
    - Curve.BinaryWeierstrass.SECT283K1
    - Curve.BinaryWeierstrass.SECT283R1
    - Curve.BinaryWeierstrass.SECT409K1
    - Curve.BinaryWeierstrass.SECT409R1
    - Curve.BinaryWeierstrass.SECT571K1
    - Curve.BinaryWeierstrass.SECT571R1
    - Curve.Montgomery
    - Curve.Montgomery.Curve448
    - Curve.Montgomery.Curve25519
    - Curve.Montgomery.Curve383187
    - Curve.Montgomery.M221
    - Curve.Montgomery.M383
    - Curve.Montgomery.M511
    - Curve.ShortWeierstrass
    - Curve.ShortWeierstrass.ANSSIFRP256V1
    - Curve.ShortWeierstrass.BLS12_381.G1
    - Curve.ShortWeierstrass.BLS12_381.G2
    - Curve.ShortWeierstrass.BN224
    - Curve.ShortWeierstrass.BN254A
    - Curve.ShortWeierstrass.BN254A2
    - Curve.ShortWeierstrass.BN254B
    - Curve.ShortWeierstrass.BN254B2
    - Curve.ShortWeierstrass.BN254P
    - Curve.ShortWeierstrass.BN254P2
    - Curve.ShortWeierstrass.BN256
    - Curve.ShortWeierstrass.BN384
    - Curve.ShortWeierstrass.BN512
    - Curve.ShortWeierstrass.SECP112R1
    - Curve.ShortWeierstrass.SECP112R2
    - Curve.ShortWeierstrass.SECP128R1
    - Curve.ShortWeierstrass.SECP128R2
    - Curve.ShortWeierstrass.SECP160K1
    - Curve.ShortWeierstrass.SECP160R1
    - Curve.ShortWeierstrass.SECP160R2
    - Curve.ShortWeierstrass.SECP192K1
    - Curve.ShortWeierstrass.SECP192R1
    - Curve.ShortWeierstrass.SECP224K1
    - Curve.ShortWeierstrass.SECP224R1
    - Curve.ShortWeierstrass.SECP256K1
    - Curve.ShortWeierstrass.SECP256R1
    - Curve.ShortWeierstrass.SECP384R1
    - Curve.ShortWeierstrass.SECP521R1
    - Curve.ShortWeierstrass.BrainpoolP160R1
    - Curve.ShortWeierstrass.BrainpoolP160T1
    - Curve.ShortWeierstrass.BrainpoolP192R1
    - Curve.ShortWeierstrass.BrainpoolP192T1
    - Curve.ShortWeierstrass.BrainpoolP224R1
    - Curve.ShortWeierstrass.BrainpoolP224T1
    - Curve.ShortWeierstrass.BrainpoolP256R1
    - Curve.ShortWeierstrass.BrainpoolP256T1
    - Curve.ShortWeierstrass.BrainpoolP320R1
    - Curve.ShortWeierstrass.BrainpoolP320T1
    - Curve.ShortWeierstrass.BrainpoolP384R1
    - Curve.ShortWeierstrass.BrainpoolP384T1
    - Curve.ShortWeierstrass.BrainpoolP512R1
    - Curve.ShortWeierstrass.BrainpoolP512T1
    - Curve.TwistedEdwards
    - Curve.TwistedEdwards.Curve1174
    - Curve.TwistedEdwards.Curve41417
    - Curve.TwistedEdwards.E222
    - Curve.TwistedEdwards.E382
    - Curve.TwistedEdwards.E521
    - Curve.TwistedEdwards.Ed448
    - Curve.TwistedEdwards.Ed3363
    - Curve.TwistedEdwards.Ed25519
    - Curve.TwistedEdwards.JubJub
  ghc-options:
    - -Wall
    - -fno-warn-orphans
  source-dirs:
    - src

tests:
  elliptic-curve-tests:
    main: Main
    dependencies:
      - tasty
      - tasty-discover
      - tasty-quickcheck
    source-dirs:
      - tests
      - src

benchmarks:
  elliptic-curve-benchmarks:
    main: Main
    dependencies:
      - criterion
    source-dirs:
      - benchmarks
      - src
