name:        jubjub
version:     0.1.0
synopsis:    JubJub Curve
description: JubJub Curve
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/jubjub
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric

dependencies:
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - galois-field

extra-source-files:
  - README.md
  - ChangeLog.md

library:
  exposed-modules:
    - JubJub
  ghc-options:
    - -Wall
  other-modules:
    - Params
    - Point
  source-dirs:
    - src

benchmarks:
  jubjub-benchmarks:
    main: Main
    dependencies:
      - base >= 4.7 && < 5
      - protolude >= 0.2
      - criterion
    source-dirs:
      - benchmarks
      - src
